website/acm/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'acm'

urlpatterns = [
    url(r'^$', views.index_view, name='index'),
    url(r'^feedback/$', views.feedback, name='feedback'),
    url(r'^upcoming/$', views.upcoming_events, name='upcoming'),
    url(r'^about/$', views.our_team_view, name='team'),

]

website/website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin.views.decorators import *
from ckeditor_uploader import views

urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'^acm/', include('acm.urls')),
                  url(r'^ckeditor/upload/', views.upload, name='ckeditor_upload'),
                  url(r'^ckeditor/browse/', views.browse, name='ckeditor_browse'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/acm/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.


class Feedback(models.Model):
    email = models.EmailField(null=False)
    content = RichTextUploadingField(config_name='default')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email+' '+str(self.created)

    def get_absolute_url(self):
        return reverse('acm:feedback_detail', kwargs={'pk': self.pk})


class UpcomingEvents(models.Model):
    title = models.CharField(max_length=100)
    content = RichTextUploadingField(config_name='default')
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

website/acm/forms.py
from django import forms
from .models import *


class FeedbackForm(forms.ModelForm):

    class Meta:
        model = Feedback
        fields = ('email', 'content')


class UpcomingEventsForm(forms.ModelForm):

    class Meta:
        model = UpcomingEvents
        fields = ('title', 'content', 'active')

website/acm/views.py
from django.shortcuts import render, redirect
from .forms import  FeedbackForm, UpcomingEventsForm
from .models import UpcomingEvents


def index_view(request):
    return render(request, 'acm/index.html', {})

def our_team_view(request):
    return render(request, 'acm/our_team.html', {})

def feedback(request):
    if request.method == "POST":
        form  = FeedbackForm(request.POST)
        if form.is_valid():
            fdbk = form.save(commit=False)
            print(fdbk)
            fdbk.save()
            return redirect('acm:index')
    else:
        form = FeedbackForm()
        return render(request, 'acm/feedback.html', {
            'form': form,
        })

def upcoming_events(request):
    events = UpcomingEvents.objects.filter(active =  True).order_by('-created')
    return render(request, 'acm/upcoming_events.html', {
        'events': events,
    })

website/acm/templates/acm/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="cache-control" content="no-cache"/>
    <meta name="expires" content="0"/>
    <meta name="pragma" content="no-cache"/>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Mono|Roboto" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" />
    <link href="{% static 'css/site.css' %}" rel="stylesheet" />
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/core.js' %}"></script>

    <style>
        body{
             font-family: 'Roboto', sans-serif;
        }
        footer{
            font-weight: bolder;
            height: auto;
        }
</style>
</head>
<body>
{% block navbar %}

{% endblock %}

<div class="container" style="width: 90%">
    <style>
    body{
        background-color: rgba(255,255,255,0.4);
    }
</style>
    {% block body_block %}

    {% endblock %}
</div>
<footer class="footer">
      <div class="container">
          Connect With Us  <span style="float: right"><img src="{% static 'images/insta20.png' %}" style="width: 100%"> </span>&nbsp;<span style="float: right"> <img src="{% static 'images/fb20.png' %}" style="width: 100%"> </span>
      </div>
    </footer>
{% block extrahead %}
    <script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>
    {{ block.super }}
{% endblock %}
</body>
</html>

website/acm/templates/acm/feedback.html
{% extends 'acm/base.html' %}
{% load staticfiles %}

{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
      <div class="container">
        <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="#">ACM STUDENT CHAPTER, NCU</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav mx-auto">
            <li class="nav-item  px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'acm:index' %}">Home</a>
            </li>
            <li class="nav-item  px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'acm:team' %}">Our Team</a>
            </li>
            <li class="nav-item  px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'acm:upcoming' %}">Upcoming Events</a>
            </li>
            <li class="nav-item active px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'acm:feedback' %}">Feedback</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
{% endblock %}
{% block body_block %}


<div class="row">
    <div class="col-sm-offset-1 col-sm-10">
        <div class="panel panel-default">
            <div class="panel-body">
                <h2>Feedback</h2>
                <hr>
                <form class="form-horizontal" enctype="multipart/form-data" action="" method="POST">
                    {% csrf_token %}

                    {% for field in form %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <span class="text-danger small">{{field.errors}}</span>
                        </div>
                        <label class="control-label col-sm-2">{{field.label_tag}}</label>
                        <div class="col-sm-10">
                            {{field}}
                        </div>
                    </div>
                    {% endfor %}
                    {{ form.media }}


                    <div class="form-group">
                        <div class="col-sm-offset-6 col-sm-2">
                            <button type="submit" class="btn btn-default">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

website/acm/templates/acm/index.html
{% extends 'acm/base.html' %}
{% load staticfiles %}
{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
      <div class="container">
        <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="#">ACM STUDENT CHAPTER, NCU</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav mx-auto">
            <li class="nav-item active  px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'acm:index' %}">Home</a>
            </li>
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'acm:team' %}">Our Team</a>
            </li>
            <li class="nav-item  px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'acm:upcoming' %}">Upcoming Events</a>
            </li>
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'acm:feedback' %}">Feedback</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
{% endblock %}
{% block body_block %}

<br>
<div>
    <div class="col-sm-10">
        <h3><b>ACM STUDENT CHAPTER, THE NORTHCAP UNIVERSITY, GURGAON</b></h3>
    </div>
</div>
<br>
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-5">
        <a href="https://www.acm.org" target="_blank"><img class="text-center" src="{% static 'images/acm.gif' %}"  style="width: 100%;vertical-align: middle;" ></a>
    </div>
    <div class="col-md-5">
        <a href="http://www.ncuindia.edu" target="_blank"><img class="text-center" src="{% static 'images/ncu.png' %}" href="http://ncuindia.edu" style="width: 100%;vertical-align: middle;height: 75%" ></a>
    </div>
    <div class="col-md-1"></div>
</div>




<div>
    <div class="col-sm-10">
        <p>Our university - <b>The NorthCap University</b> is a multi-disciplinary University, offering various Undergraduate and Postgraduate courses in Engineering, Law and Management. As per National Institutional Ranking Framework (NIRF), introduced by HRD Ministry, the University has been ranked 82nd among all the universities in India. Also it is the only private university in Delhi NCR to secure a rank in top 100 universities, across the country.</p>
    </div>
</div>
<div>
    <div class="col-sm-10">
        <b>What is ACM?</b> - <a target="_blank" href="https://www.acm.org">www.acm.org</a> ACM brings together computing educators, researchers, and professionals to inspire dialogue, share resources, and address the field's challenges. ACM strengthens the profession's collective voice through strong leadership, promotion of the highest standards, and recognition of technical excellence. ACM provides opportunities for lifelong learning, career development, and professional networking.

    </div>
</div>
<div>
    <div class="col-sm-10">
<b>What is our aim?</b> - Through this student chapter, we hope to encourage students to diligently pursue their interest in computer technologies and contribute towards the revolution our world is moving towards. With the help of our faculties, along with support from ACM, we hope to create lucrative and proficient computer engineers.

    </div>
</div>

<div>
    <div class="col-sm-10">
        <b>Our team</b> - Our chairperson, Meghna Sharma and our co-chair,Jatin Bhati, along with our faculty support Latika Dhulia, have formed a capable and creative team of developers, artists, PR practitioners and organizers. Our web development team is lead by Deepanshu Jain and has done a great work with our website. Our group of content writers work under Chhavi Jain and show their magic with our reports and articles. Garima handles our social media with a team of socially very active people. The event organizers and the graphic designers work with Jatin to manage the very successful events we conduct regularly. We are very proud of our team for building our student chapter to what it is today.

    </div>
</div>


{% endblock %}

website/acm/templates/acm/our_team.html
{% extends 'acm/base.html' %}
{% load staticfiles %}

{% block navbar %}
<style>
    img {
        width: 90%;
    }

</style>

<nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
    <div class="container">
        <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="#">ACM STUDENT CHAPTER,
            NCU</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item  px-lg-4">
                    <a class="nav-link text-uppercase text-expanded" href="{% url 'acm:index' %}">Home</a>
                </li>
                <li class="nav-item active px-lg-4">
                    <a class="nav-link text-uppercase text-expanded" href="{% url 'acm:team' %}">Our Team</a>
                </li>
                <li class="nav-item  px-lg-4">
                    <a class="nav-link text-uppercase text-expanded" href="{% url 'acm:upcoming' %}">Upcoming Events</a>
                </li>
                <li class="nav-item px-lg-4">
                    <a class="nav-link text-uppercase text-expanded" href="{% url 'acm:feedback' %}">Feedback</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% endblock %}
{% block body_block %}
<br>
<h2>Our Team</h2>

<div class="row" style="width: 100%">
    <div class="col-md-3" style="width: 90%;float:left; margin: 1%; ">
        <div class="card" style="width: 17rem;">
            <img class="card-img-top" src="{% static 'images/fake.svg' %}" alt="Card image cap">
            <div class="card-block">
                <h4 class="card-title">Card title</h4>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
        </div>
    </div>

    <div class="col-md-3" style="width: 90%;float:left; margin: 1%; ">
        <div class="card" style="width: 17rem;">
            <img class="card-img-top" src="{% static 'images/fake.svg' %}" alt="Card image cap">
            <div class="card-block">
                <h4 class="card-title">Card title</h4>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
        </div>
    </div>
    <div class="col-md-3" style="width: 90%;float:left; margin: 1%;">
        <div class="card" style="width: 17rem">
            <img class="card-img-top" src="{% static 'images/fake.svg' %}" alt="Card image cap">
            <div class="card-block">
                <h4 class="card-title">Card title</h4>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
        </div>
    </div>
</div>

<div class="row" style="width: 100%">
    <div class="col-md-3" style="width: 90%;float:left; margin: 1%; ">
        <div class="card" style="width: 17rem;">
            <img class="card-img-top" src="{% static 'images/fake.svg' %}" alt="Card image cap">
            <div class="card-block">
                <h4 class="card-title">Card title</h4>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
        </div>
    </div>

    <div class="col-md-3" style="width: 90%;float:left; margin: 1%; ">
        <div class="card" style="width: 17rem;">
            <img class="card-img-top" src="{% static 'images/fake.svg' %}" alt="Card image cap">
            <div class="card-block">
                <h4 class="card-title">Card title</h4>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
        </div>
    </div>
    <div class="col-md-3" style="width: 90%;float:left; margin: 1%;">
        <div class="card" style="width: 17rem">
            <img class="card-img-top" src="{% static 'images/fake.svg' %}" alt="Card image cap">
            <div class="card-block">
                <h4 class="card-title">Card title</h4>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/acm/templates/acm/upcoming_events.html
{% extends 'acm/base.html' %}
{% load staticfiles %}

{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
      <div class="container">
        <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="#">ACM STUDENT CHAPTER, NCU</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav mx-auto">
            <li class="nav-item  px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'acm:index' %}">Home</a>
            </li>
            <li class="nav-item  px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'acm:team' %}">Our Team</a>
            </li>
            <li class="nav-item active px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'acm:upcoming' %}">Upcoming Events</a>
            </li>
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'acm:feedback' %}">Feedback</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
{% endblock %}
{% block body_block %}
<br>
<h2>Upcoming events:</h2>

{% for event in events %}
<div class="card" style="background-color:rgba(0, 0,0,0.1);border: 3px solid #cccccc; padding:10px; width: 100%">

    <div class="card-block">
        <h4 class="card-title">
            {{ event.title }}
        </h4>
        <p class="card-text" >
            {{ event.content|safe }}
        </p>
    </div>
    </div>
<br>
{% endfor %}

{% endblock %}